version: '3'

services:

  app:
     build: .
     volumes:
       - .:/home/python/app
     ports:
      - 8000:8000
     depends_on:
      - db  # Django depends on the PostgreSQL database to be ready

  # PostgreSQL database container
  db:
    image: postgres:13
    volumes:
       - ./postgres_data:/var/lib/postgresql/data:rw  # Persistent data volume for PostgreSQL