# Generated by Django 5.0.4 on 2024-04-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(to='app.question', verbose_name='Pergunta'),
        ),
    ]
